### PR TITLE
Update to v0.5.0

### PR DESCRIPTION
**Pull request by marcoesters**
orjson -> cargo-bundle-licenses

# Package Info

Home: https://github.com/sstadick/cargo-bundle-licenses
Development: https://github.com/sstadick/cargo-bundle-licenses
Documentation: https://github.com/sstadick/cargo-bundle-licenses

### CODE REVIEW

**Review by varlackc — COMMENTED** [review]
The following changes might be recomended:

license_url: https://github.com/sstadick/cargo-bundle-licenses/blob/main/LICENSE-APACHE
license_url: https://github.com/sstadick/cargo-bundle-licenses/blob/main/LICENSE-MIT

doc_source_url: https://github.com/sstadick/cargo-bundle-licenses/blob/main/README.md

might need to change the doc_url to the following:

doc_url: https://github.com/sstadick/cargo-bundle-licenses/blob/main/README.md

**Comment by marcoesters** [comment]
> The following changes might be recomended:
> 
> license_url: https://github.com/sstadick/cargo-bundle-licenses/blob/main/LICENSE-APACHE license_url: https://github.com/sstadick/cargo-bundle-licenses/blob/main/LICENSE-MIT
> 
> doc_source_url: https://github.com/sstadick/cargo-bundle-licenses/blob/main/README.md
> 
> might need to change the doc_url to the following:
> 
> doc_url: https://github.com/sstadick/cargo-bundle-licenses/blob/main/README.md

Can you use two license URLs? The linter crashes when you do and since it's not a hard requirement, I would skip this for now.

I think the doc_url is good the way it is. It points to the same file anyway.

**Review by skupr-anaconda — APPROVED** [review]
LGTM

**Review by psteyer — APPROVED** [review]
LGTM

**Review by varlackc — APPROVED** [review]
LGTM we just have to make sure that we can build for `win-64`

**Pull request merged**
